<?php

/* 
 * Copyright (C) 2014 Mihai Chelaru
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

final class GdbcCountryDataSource
{

	private static $arrCountry = array(
		1 => array("Afghanistan", "AF"),
		2 => array("Aland Islands", "AX"),
		3 => array("Albania", "AL"),
		4 => array("Algeria", "DZ"),
		5 => array("American Samoa", "AS"),
		6 => array("Andorra", "AD"),
		7 => array("Angola", "AO"),
		8 => array("Anguilla", "AI"),
		9 => array("Antarctica", "AQ"),
		10 => array("Antigua and Barbuda", "AG"),
		11 => array("Argentina", "AR"),
		12 => array("Armenia", "AM"),
		13 => array("Aruba", "AW"),
		14 => array("Australia", "AU"),
		15 => array("Austria", "AT"),
		16 => array("Azerbaijan", "AZ"),
		17 => array("Bahamas", "BS"),
		18 => array("Bahrain", "BH"),
		19 => array("Bangladesh", "BD"),
		20 => array("Barbados", "BB"),
		21 => array("Belarus", "BY"),
		22 => array("Belgium", "BE"),
		23 => array("Belize", "BZ"),
		24 => array("Benin", "BJ"),
		25 => array("Bermuda", "BM"),
		26 => array("Bhutan", "BT"),
		27 => array("Bolivia", "BO"),
		28 => array("Bosnia and Herzegovina", "BA"),
		29 => array("Botswana", "BW"),
		30 => array("Bouvet island", "BV"),
		31 => array("Brazil", "BR"),
		32 => array("British Indian Ocean", "IO"),
		33 => array("Brunei Darussalam", "BN"),
		34 => array("Bulgaria", "BG"),
		35 => array("Burkina Faso", "BF"),
		36 => array("Burundi", "BI"),
		37 => array("Cambodia", "KH"),
		38 => array("Cameroon", "CM"),
		39 => array("Canada", "CA"),
		40 => array("Cape Verde", "CV"),
		41 => array("Cayman Islands", "KY"),
		42 => array("Central African Republic", "CF"),
		43 => array("Chad", "TD"),
		44 => array("Chile", "CL"),
		45 => array("China", "CN"),
		46 => array("Christmas Island", "CX"),
		47 => array("Cocos Islands", "CC"),
		48 => array("Colombia", "CO"),
		49 => array("Comoros", "KM"),
		50 => array("Congo", "CG"),
		51 => array("Congo", "CD"),
		52 => array("Cook Islands", "CK"),
		53 => array("Costa Rica", "CR"),
		54 => array("Cote d'Ivoire", "CI"),
		55 => array("Croatia", "HR"),
		56 => array("Cuba", "CU"),
		57 => array("Cyprus", "CY"),
		58 => array("Czech Republic", "CZ"),
		59 => array("Denmark", "DK"),
		60 => array("Djibouti", "DJ"),
		61 => array("Dominica", "DM"),
		62 => array("Dominican republic", "DO"),
		63 => array("Ecuador", "EC"),
		64 => array("Egypt", "EG"),
		65 => array("El Salvador", "SV"),
		66 => array("Equatorial Guinea", "GQ"),
		67 => array("Eritrea", "ER"),
		68 => array("Estonia", "EE"),
		69 => array("Ethiopia", "ET"),
		70 => array("Falkland Islands", "FK"),
		71 => array("Faroe Islands", "FO"),
		72 => array("Fiji", "FJ"),
		73 => array("Finland", "FI"),
		74 => array("France", "FR"),
		75 => array("French Guiana", "GF"),
		76 => array("French Polynesia", "PF"),
		77 => array("French Southern Territories", "TF"),
		78 => array("Gabon", "GA"),
		79 => array("Gambia", "GM"),
		80 => array("Georgia", "GE"),
		81 => array("Germany", "DE"),
		82 => array("Ghana", "GH"),
		83 => array("Gibraltar", "GI"),
		84 => array("Greece", "GR"),
		85 => array("Greenland", "Gl"),
		86 => array("Grenada", "GD"),
		87 => array("Guadeloupe", "GP"),
		88 => array("Guam", "GU"),
		89 => array("Guatemala", "GT"),
		90 => array("Guernsey", "GG"),
		91 => array("Guinea", "GN"),
		92 => array("Guinea-Bissau", "GW"),
		93 => array("Guyana", "GY"),
		94 => array("Haiti", "HT"),
		95 => array("Heard and Mcdonald Islands", "HM"),
		96 => array("Vatican", "VA"),
		97 => array("Honduras", "HN"),
		98 => array("Hong Kong", "HK"),
		99 => array("Hungary", "HU"),
		100 => array("Iceland", "IS"),
		101 => array("India", "IN"),
		102 => array("Indonesia", "ID"),
		103 => array("Iran", "IR"),
		104 => array("Iraq", "IQ"),
		105 => array("Ireland", "IE"),
		106 => array("Isle of Man", "IM"),
		107 => array("Israel", "IL"),
		108 => array("Italy", "IT"),
		109 => array("Jamaica", "JM"),
		110 => array("Japan", "JP"),
		111 => array("Jersey", "JE"),
		112 => array("Jordan", "JO"),
		113 => array("Kazakhstan", "KZ"),
		114 => array("Kenya", "KE"),
		115 => array("Kiribati", "KI"),
		116 => array("Korea", "KP"),
		117 => array("Korea", "KR"),
		118 => array("Kuwait", "KW"),
		119 => array("Kyrgyzstan", "KG"),
		120 => array("Lao Republic", "LA"),
		121 => array("Latvia", "LV"),
		122 => array("Lebanon", "LB"),
		123 => array("Lesotho", "LS"),
		124 => array("Liberia", "LR"),
		125 => array("Libyan Arab Jamahiriya", "LY"),
		126 => array("Liechtenstein", "LI"),
		127 => array("Lithuania", "LT"),
		128 => array("Luxembourg", "LU"),
		129 => array("Macao", "MO"),
		130 => array("Macedonia", "MK"),
		131 => array("Madagascar", "MG"),
		132 => array("Malawi", "MW"),
		133 => array("Malaysia", "MY"),
		134 => array("Maldives", "MV"),
		135 => array("Mali", "Ml"),
		136 => array("Malta", "MT"),
		137 => array("Marshall Islands", "MH"),
		138 => array("Martinique", "MQ"),
		139 => array("Mauritania", "MR"),
		140 => array("Mauritius", "MU"),
		141 => array("Mayotte", "YT"),
		142 => array("Mexico", "MX"),
		143 => array("Micronesia", "FM"),
		144 => array("Moldova", "MD"),
		145 => array("Monaco", "MC"),
		146 => array("Mongolia", "MN"),
		147 => array("Montenegro", "ME"),
		148 => array("Montserrat", "MS"),
		149 => array("Morocco", "MA"),
		150 => array("Mozambique", "MZ"),
		151 => array("Myanmar", "MM"),
		152 => array("Namibia", "NA"),
		153 => array("Nauru", "NR"),
		154 => array("Nepal", "NP"),
		155 => array("Netherlands", "NL"),
		156 => array("Netherlands Antilles", "AN"),
		157 => array("New Caledonia", "NC"),
		158 => array("New Zealand", "NZ"),
		159 => array("Nicaragua", "NI"),
		160 => array("Niger", "NE"),
		161 => array("Nigeria", "NG"),
		162 => array("Niue", "NU"),
		163 => array("Norfolk Island", "NF"),
		164 => array("Northern Mariana Islands", "MP"),
		165 => array("Norway", "NO"),
		166 => array("Oman", "OM"),
		167 => array("Pakistan", "PK"),
		168 => array("Palau", "PW"),
		169 => array("Palestinian Territory Occupied", "PS"),
		170 => array("Panama", "PA"),
		171 => array("Papua New Guinea", "PG"),
		172 => array("Paraguay", "PY"),
		173 => array("Peru", "PE"),
		174 => array("Philippines", "PH"),
		175 => array("Pitcairn", "PN"),
		176 => array("Poland", "PL"),
		177 => array("Portugal", "PT"),
		178 => array("Puerto rico", "PR"),
		179 => array("Qatar", "QA"),
		180 => array("Reunion", "RE"),
		181 => array("Romania", "RO"),
		182 => array("Russian Federation", "RU"),
		183 => array("Rwanda", "RW"),
		184 => array("Saint Barthelemy", "BL"),
		185 => array("Saint Helena", "SH"),
		186 => array("Saint Kitts and Nevis", "KN"),
		187 => array("Saint Lucia", "LC"),
		188 => array("Saint Martin", "MF"),
		189 => array("Saint Pierre and Miquelon", "PM"),
		190 => array("Saint Vincent", "VC"),
		191 => array("Samoa", "WS"),
		192 => array("San Marino", "SM"),
		193 => array("Sao Tome and Principe", "ST"),
		194 => array("Saudi Arabia", "SA"),
		195 => array("Senegal", "SN"),
		196 => array("Serbia", "RS"),
		197 => array("Seychelles", "SC"),
		198 => array("Sierra Leone", "SL"),
		199 => array("Singapore", "SG"),
		200 => array("Slovakia", "SK"),
		201 => array("Slovenia", "SI"),
		202 => array("Solomon Islands", "SB"),
		203 => array("Somalia", "SO"),
		204 => array("South Africa", "ZA"),
		205 => array("South Georgia and Islands", "GS"),
		206 => array("Spain", "ES"),
		207 => array("Sri Lanka", "LK"),
		208 => array("Sudan", "SD"),
		209 => array("Suriname", "SR"),
		210 => array("Svalbard and Jan Mayen", "SJ"),
		211 => array("Swaziland", "SZ"),
		212 => array("Sweden", "SE"),
		213 => array("Switzerland", "CH"),
		214 => array("Syrian Arab Republic", "SY"),
		215 => array("Taiwan", "TW"),
		216 => array("Tajikistan", "TJ"),
		217 => array("Tanzania", "TZ"),
		218 => array("Thailand", "TH"),
		219 => array("Timor-Leste", "TL"),
		220 => array("Togo", "TG"),
		221 => array("Tokelau", "TK"),
		222 => array("Tonga", "TO"),
		223 => array("Trinidad and Tobago", "TT"),
		224 => array("Tunisia", "TN"),
		225 => array("Turkey", "TR"),
		226 => array("Turkmenistan", "TM"),
		227 => array("Turks and Caicos Islands", "TC"),
		228 => array("Tuvalu", "TV"),
		229 => array("Uganda", "UG"),
		230 => array("Ukraine", "UA"),
		231 => array("United Arab Emirates", "AE"),
		232 => array("United Kingdom", "GB"),
		233 => array("United States", "US"),
		234 => array("United States Minor Islands", "UM"),
		235 => array("Uruguay", "UY"),
		236 => array("Uzbekistan", "UZ"),
		237 => array("Vanuatu", "VU"),
		238 => array("Venezuela", "VE"),
		239 => array("Viet Nam", "VN"),
		240 => array("Virgin Islands British", "VG"),
		241 => array("Virgin Islands U.S.", "VI"),
		242 => array("Wallis and Futuna", "WF"),
		243 => array("Western Sahara", "EH"),
		244 => array("Yemen", "YE"),
		245 => array("Zambia", "ZM"),
		246 => array("Zimbabwe", "ZW")
	);

	public static function getCountryIdByCode($countryCode)
	{
		$countryCode = trim(strtoupper($countryCode));

		foreach (self::$arrCountry as $key => $value)
			if ($countryCode === $value[1])
				return $key;

		return 0;
	}

	public static function getCountryCodeById($countryId)
	{
		return isset(self::$arrCountry[$countryId][1]) ? self::$arrCountry[$countryId][1] : null;
	}

	public static function getCountryNameById($countryId)
	{
		return isset(self::$arrCountry[$countryId][0]) ? self::$arrCountry[$countryId][0] : null;
	}
}
